# Generated by Django 4.0.4 on 2022-06-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vmModel',
            fields=[
                ('vm_id', models.AutoField(primary_key=True, serialize=False)),
                ('vm_name', models.CharField(help_text='vm_name', max_length=50)),
                ('os', models.CharField(help_text=' os', max_length=50)),
                ('storage', models.CharField(help_text='storage', max_length=50)),
                ('storage_type', models.CharField(help_text='storage_type', max_length=50, null=True)),
                ('cpu', models.CharField(help_text='cpu', max_length=50)),
                ('ram', models.CharField(help_text='ram', max_length=200)),
                ('vm_added_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=50, null='True')),
                ('radio', models.CharField(default='Pending', max_length=50, null='True')),
            ],
            options={
                'db_table': 'vm_details',
            },
        ),
    ]
