# Generated by Django 4.0.4 on 2022-06-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='requestModel',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(null=True)),
                ('vm_id', models.IntegerField(null=True)),
                ('file_id', models.IntegerField(null=True)),
                ('file', models.FileField(null=True, upload_to='files/')),
                ('file_name', models.CharField(help_text='file_name', max_length=200)),
                ('description', models.CharField(help_text='description', max_length=250, null=True)),
                ('file_size', models.BigIntegerField(help_text='file_size', null=True)),
                ('file_type', models.CharField(help_text='file_type', max_length=300)),
                ('file_data', models.TextField(null=True)),
                ('status', models.CharField(default='Pending', max_length=50, null='True')),
                ('requested_date', models.DateField(auto_now_add=True, null=True)),
                ('requested_time', models.TimeField(auto_now_add=True, null=True)),
                ('file_uploaded_date', models.DateField(null=True)),
                ('file_uploaded_time', models.TimeField(null=True)),
                ('differenced_time', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'request_details',
            },
        ),
    ]
