# Generated by Django 4.0.4 on 2022-06-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmodel',
            name='differenced_time',
            field=models.TimeField(null=True),
        ),
    ]
