# Generated by Django 4.0.4 on 2022-06-22 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerapp', '0002_alter_requestmodel_differenced_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestmodel',
            name='status',
        ),
    ]
