# Generated by Django 4.0.4 on 2022-06-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerapp', '0004_alter_requestmodel_differenced_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmodel',
            name='file_uploaded_time',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='requestmodel',
            name='requested_time',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
