# Generated by Django 4.0.4 on 2022-06-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fileModel',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(null=True)),
                ('vm_id', models.IntegerField(null=True)),
                ('file', models.FileField(null=True, upload_to='files/')),
                ('file_name', models.CharField(help_text='file_name', max_length=200)),
                ('description', models.CharField(help_text='description', max_length=250, null=True)),
                ('file_extension', models.CharField(help_text='file_extension', max_length=250, null=True)),
                ('file_size', models.BigIntegerField(help_text='file_size', null=True)),
                ('file_type', models.CharField(help_text='file_type', max_length=300)),
                ('file_key', models.CharField(max_length=200, null=True)),
                ('file_data', models.TextField(null=True)),
                ('status1', models.CharField(max_length=50, null='True')),
                ('status', models.CharField(default='Pending', max_length=50, null='True')),
                ('file_uploaded_date', models.DateField(auto_now_add=True, null=True)),
                ('file_uploaded_time', models.TimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'file_details',
            },
        ),
        migrations.CreateModel(
            name='userModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(help_text='user_name', max_length=50)),
                ('email', models.EmailField(help_text=' email', max_length=50)),
                ('password', models.CharField(help_text='password', max_length=50)),
                ('mobile', models.BigIntegerField(help_text='mobile')),
                ('location', models.CharField(help_text='location', max_length=200)),
                ('dob', models.DateField(help_text='dob')),
                ('user_image', models.ImageField(null=True, upload_to='user_image')),
                ('otp', models.IntegerField(null=True)),
                ('verification', models.CharField(default='Pending', max_length=50)),
                ('status', models.CharField(default='Pending', max_length=50, null='True')),
                ('reg_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
    ]
